#!/usr/bin/env python3
"""Generate the Kiro power at powers/buildkite/ from skills/buildkite-*/SKILL.md.

Source of truth: skills/buildkite-*/SKILL.md (the Claude/Cursor skills).
Generated outputs (do not hand-edit):
  - powers/buildkite/steering/<short>.md     (steering file per skill)
  - powers/buildkite/steering/<short>/{references,examples}/  (symlinks)
"""

import os
import re
import shutil
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
POWER_DIR = REPO / "powers" / "buildkite"
STEERING_DIR = POWER_DIR / "steering"

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/build-power.py from skills/{src}/SKILL.md. "
    "Do not edit by hand. -->\n\n"
)


def parse_skill(skill_md: Path):
    text = skill_md.read_text()
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not m:
        raise SystemExit(f"{skill_md}: missing YAML frontmatter")
    meta = yaml.safe_load(m.group(1))
    body = m.group(2).lstrip("\n")
    return meta, body


def rewrite_links(body: str, short: str) -> str:
    """Rewrite `references/foo` and `examples/foo` to `<short>/references/foo`."""
    return re.sub(
        r"`(references|examples)/([^`]+)`",
        rf"`{short}/\1/\2`",
        body,
    )


def write_steering_file(short: str, src: str, meta: dict, body: str) -> None:
    STEERING_DIR.mkdir(parents=True, exist_ok=True)
    out = STEERING_DIR / f"{short}.md"
    description = " ".join(meta["description"].split())
    frontmatter = {
        "inclusion": "auto",
        "name": meta["name"],
        "description": description,
    }
    yaml_block = yaml.safe_dump(
        frontmatter, sort_keys=False, default_flow_style=False, width=10_000
    ).rstrip()
    content = f"---\n{yaml_block}\n---\n\n{GENERATED_HEADER.format(src=src)}{body}"
    if not content.endswith("\n"):
        content += "\n"
    out.write_text(content)


def ensure_symlink(link: Path, target_rel: str) -> None:
    if link.is_symlink() or link.exists():
        if link.is_symlink() and os.readlink(link) == target_rel:
            return
        if link.is_dir() and not link.is_symlink():
            shutil.rmtree(link)
        else:
            link.unlink()
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(target_rel)


def link_resources(short: str, src: str) -> None:
    src_dir = SKILLS_DIR / src
    bundle_dir = STEERING_DIR / short
    any_linked = False
    for sub in ("references", "examples"):
        if (src_dir / sub).is_dir():
            link = bundle_dir / sub
            # link sits at powers/buildkite/steering/<short>/<sub>
            # target sits at skills/<src>/<sub>
            # relative: up 4 (sub -> short -> steering -> buildkite -> powers -> REPO)
            target = f"../../../../skills/{src}/{sub}"
            ensure_symlink(link, target)
            any_linked = True
    if not any_linked and bundle_dir.exists() and not any(bundle_dir.iterdir()):
        bundle_dir.rmdir()


def clean_orphans(active_shorts: set[str]) -> None:
    if not STEERING_DIR.exists():
        return
    for entry in STEERING_DIR.iterdir():
        if entry.is_file() and entry.suffix == ".md":
            if entry.stem not in active_shorts:
                entry.unlink()
        elif entry.is_dir():
            if entry.name not in active_shorts:
                shutil.rmtree(entry)


def main() -> int:
    skills = sorted(p for p in SKILLS_DIR.glob("buildkite-*") if (p / "SKILL.md").exists())
    if not skills:
        print("No skills/buildkite-*/SKILL.md found", file=sys.stderr)
        return 1

    active = set()
    for skill_dir in skills:
        src = skill_dir.name
        short = src.removeprefix("buildkite-")
        active.add(short)
        meta, body = parse_skill(skill_dir / "SKILL.md")
        body = rewrite_links(body, short)
        write_steering_file(short, src, meta, body)
        link_resources(short, src)
        print(f"  steering/{short}.md")

    clean_orphans(active)
    return 0


if __name__ == "__main__":
    sys.exit(main())
